#
# Copyright (C) 2025 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/samsung/a34x

AB_OTA_UPDATER := false

ALLOW_MISSING_DEPENDENCIES := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true
BUILD_BROKEN_ENFORCE_VINTF_MANIFEST := true
BUILD_BROKEN_USES_BUILD_DATE_TOOL := true

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 := 
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := cortex-a55

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic
TARGET_2ND_CPU_VARIANT_RUNTIME := cortex-a55

# Bootloader
BOARD_VENDOR := samsung
TARGET_SOC := mt6877
TARGET_BOOTLOADER_BOARD_NAME := a34x
TARGET_BOARD_PLATFORM := $(TARGET_SOC)
TARGET_BOARD_PLATFORM_GPU := Mali-G68 MC4
TARGET_NO_BOOTLOADER := true
BOARD_USES_MTK_HARDWARE := true
MTK_HARDWARE := true

# Display
TARGET_SCREEN_DENSITY := 390
TARGET_SCREEN_HEIGHT := 1080
TARGET_SCREEN_WIDTH := 2340
TARGET_USES_VULKAN := true

# Kernel
BOARD_BOOT_HEADER_VERSION := 4
BOARD_INIT_BOOT_HEADER_VERSION := 4
BOARD_KERNEL_BASE := 0x40078000
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2 loop.max_part=7
BOARD_KERNEL_CMDLINE += androidboot.selinux=permissive
BOARD_KERNEL_PAGESIZE := 4096
BOARD_KERNEL_IMAGE_NAME := Image
TARGET_KERNEL_CONFIG := a34x_defconfig
TARGET_KERNEL_SOURCE := kernel/samsung/a34x
TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_CLANG_COMPILE := true
TARGET_KERNEL_VERSION := 6.6.50

# Kernel - prebuilt
TARGET_FORCE_PREBUILT_KERNEL := true
TARGET_USES_PREBUILT_KERNEL := true
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilts/kernel
TARGET_PREBUILT_DTB := $(DEVICE_PATH)/prebuilts/dtb.img
BOARD_PREBUILT_RECOVERY_DTB := $(DEVICE_PATH)/prebuilts/recovery_dtb.img
BOARD_PREBUILT_DTBOIMAGE := $(DEVICE_PATH)/prebuilts/dtbo.img
BOARD_PREBUILT_RECOVERY_DTBOIMAGE := $(DEVICE_PATH)/prebuilts/recovery_dtbo.img
BOARD_PREBUILT_INIT_BOOTIMAGE := $(DEVICE_PATH)/prebuilts/init_boot.img
BOARD_MKBOOTIMG_ARGS := --base=0x40078000 --ramdisk_offset=0x11088000 --second_offset=0xbff88000 --dtb_offset=0x07c08000 --os_version=15.0.0 --tags_offset=0x07c08000 --header_version=4
BOARD_RECOVERY_MKBOOTIMG_ARGS := \
    --base=0x40078000 \
    --ramdisk_offset=0x11088000 \
    --second_offset=0xbff88000 \
    --dtb_offset=0x07c08000 \
    --os_version=15.0.0 \
    --tags_offset=0x07c08000 \
    --board=SRPVL02A010 \
    --header_version=2
BOARD_ROOT_EXTRA_FOLDERS := \
    efs \
    optics \
    prism \
    spu \
    system_dlkm \
    carrier
BOARD_ROOT_EXTRA_SYMLINKS := /sys/kernel/debug:d
BOARD_SUPPRESS_SECURE_ERASE := true

# Partitions
BOARD_FLASH_BLOCK_SIZE := 262144 # (BOARD_KERNEL_PAGESIZE * 64)
BOARD_BOOTIMAGE_PARTITION_SIZE := 33554432
BOARD_DTBO_PARTITION_SIZE := 299008
BOARD_DTBOIMG_PARTITION_SIZE := 299008
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 67108864
BOARD_INIT_BOOT_IMAGE_PARTITION_SIZE := 8388608
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_SUPER_PARTITION_SIZE := 9126805504 # TODO: Fix hardcoded value
BOARD_SUPER_PARTITION_GROUPS := samsung_dynamic_partitions
BOARD_SAMSUNG_DYNAMIC_PARTITIONS_PARTITION_LIST := odm product system system_ext vendor system_dlkm vendor_dlkm odm_dlkm
BOARD_SAMSUNG_DYNAMIC_PARTITIONS_SIZE := 9122611200 # TODO: Fix hardcoded value

BOARD_BUILD_VENDOR_RAMDISK_IMAGE := true
BOARD_USES_SYSTEM_DLKM_PARTITION := true
BOARD_USES_VENDOR_DLKM_PARTITION := true
BOARD_USES_METADATA_PARTITION := true
BOARD_USES_PRODUCTIMAGE := true
BOARD_BUILD_SYSTEM_DLKM_IMAGE := false

BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_SYSTEM_EXTIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_ODMIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_SYSTEM_DLKMIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_VENDOR_DLKMIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_ODM_DLKMIMAGE_FILE_SYSTEM_TYPE := erofs

TARGET_COPY_OUT_VENDOR := vendor
TARGET_COPY_OUT_ODM := odm
TARGET_COPY_OUT_PRODUCT := product
TARGET_COPY_OUT_SYSTEM_EXT := system_ext
TARGET_COPY_OUT_SYSTEM_DLKM := system_dlkm
TARGET_COPY_OUT_VENDOR_DLKM := vendor_dlkm
TARGET_COPY_OUT_ODM_DLKM := odm_dlkm

# Properties
TARGET_SYSTEM_PROP += $(DEVICE_PATH)/etc/props/system.prop
TARGET_VENDOR_PROP += $(DEVICE_PATH)/etc/props/vendor.prop
TARGET_PRODUCT_PROP += $(DEVICE_PATH)/etc/props/product.prop
TARGET_SYSTEM_EXT_PROP += $(DEVICE_PATH)/etc/props/system_ext.prop
TARGET_SYSTEM_DLKM_PROP += $(DEVICE_PATH)/etc/props/system_dlkm.prop
TARGET_ODM_PROP += $(DEVICE_PATH)/etc/props/odm.prop
TARGET_ODM_DLKM_PROP += $(DEVICE_PATH)/etc/props/odm_dlkm.prop
TARGET_VENDOR_DLKM_PROP += $(DEVICE_PATH)/etc/props/vendor_dlkm.prop

# Recovery
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/rootdir/etc/fstab.mt6877
BOARD_HAS_DOWNLOAD_MODE := true
BOARD_INCLUDE_RECOVERY_DTBO := true
BOARD_KERNEL_SEPARATED_DTBO := true
BOARD_USES_FULL_RECOVERY_IMAGE := true
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
TARGET_USES_MKE2FS := true

# Security patch level
BOOT_SECURITY_PATCH := 2026-01-01
VENDOR_SECURITY_PATCH := $(BOOT_SECURITY_PATCH)

# Verified Boot
BOARD_AVB_ENABLE := true
BOARD_AVB_BOOT_ALGORITHM := SHA256_RSA4096
BOARD_AVB_BOOT_KEY_PATH := external/avb/test/data/testkey_rsa4096.pem
BOARD_AVB_BOOT_ROLLBACK_INDEX := 0
BOARD_AVB_BOOT_ROLLBACK_INDEX_LOCATION := 0
BOARD_AVB_RECOVERY_ALGORITHM := SHA256_RSA4096
BOARD_AVB_RECOVERY_KEY_PATH := external/avb/test/data/testkey_rsa4096.pem
BOARD_AVB_RECOVERY_ROLLBACK_INDEX := 0
BOARD_AVB_RECOVERY_ROLLBACK_INDEX_LOCATION := 1
BOARD_AVB_VBMETA_SYSTEM := product system system_ext
BOARD_AVB_VBMETA_SYSTEM_ALGORITHM := SHA256_RSA4096
BOARD_AVB_VBMETA_SYSTEM_KEY_PATH := external/avb/test/data/testkey_rsa4096.pem
BOARD_AVB_VBMETA_SYSTEM_ROLLBACK_INDEX := 0
BOARD_AVB_VBMETA_SYSTEM_ROLLBACK_INDEX_LOCATION := 2
BOARD_AVB_VBMETA_VENDOR := odm vendor system_dlkm vendor_dlkm odm_dlkm vendor_boot dtbo
BOARD_AVB_VBMETA_VENDOR_ALGORITHM := SHA256_RSA4096
BOARD_AVB_VBMETA_VENDOR_KEY_PATH := external/avb/test/data/testkey_rsa4096.pem
BOARD_AVB_VBMETA_VENDOR_ROLLBACK_INDEX := 0
BOARD_AVB_VBMETA_VENDOR_ROLLBACK_INDEX_LOCATION := 3
BOARD_AVB_INIT_BOOT_ALGORITHM := SHA256_RSA4096
BOARD_AVB_INIT_BOOT_KEY_PATH := external/avb/test/data/testkey_rsa4096.pem
BOARD_AVB_INIT_BOOT_ROLLBACK_INDEX := 0
BOARD_AVB_INIT_BOOT_ROLLBACK_INDEX_LOCATION := 4

BOARD_VNDK_VERSION := current

# IMS
BOARD_USES_MTK_IMS := true

# RIL
ENABLE_VENDOR_RIL_SERVICE := true

# Bluetooth
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := $(DEVICE_PATH)/bluetooth/include
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_MTK := true

# NFC
BOARD_NFC_CHIPSET := sec_s3nrn4v

# Wi-Fi
BOARD_HOSTAPD_DRIVER := NL80211
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
WIFI_DRIVER_FW_PATH_STA      := "STA"
WIFI_DRIVER_FW_PATH_AP       := "AP"
WIFI_DRIVER_FW_PATH_P2P      := "P2P"
WIFI_DRIVER_FW_PATH_PARAM    := "/dev/wmtWifi"
WIFI_DRIVER_STATE_CTRL_PARAM := "/dev/wmtWifi"
WIFI_DRIVER_STATE_ON         := "1"
WIFI_DRIVER_STATE_OFF        := "0"
WIFI_HIDL_UNIFIED_SUPPLICANT_SERVICE_RC_ENTRY := true
WPA_SUPPLICANT_VERSION := VER_0_8_X

# Do NOT set BOARD_WLAN_DEVICE := MediaTek
# Leave it unset so it falls to conditions_default  libwifi-hal-fallback
WIFI_MULTIPLE_VENDOR_HALS := true

# Charger
BOARD_CHARGER_ENABLE_SUSPEND := true

# Sepolicy
include device/mediatek/sepolicy_vndr/SEPolicy.mk
BOARD_SEPOLICY_DIRS += \
    hardware/mediatek/sepolicy/bsp/vendor \
    hardware/samsung/sepolicy/common \
    hardware/samsung/sepolicy/mtk \
    device/samsung/a34x/sepolicy/vendor

TARGET_FS_CONFIG_GEN := $(DEVICE_PATH)/etc/config.fs

# VINTF
DEVICE_MANIFEST_FILE += $(DEVICE_PATH)/etc/vintf/manifest.xml
DEVICE_MATRIX_FILE += $(DEVICE_PATH)/etc/vintf/compatibility_matrix.device.xml

# odm
ODM_MANIFEST_SKUS := dsds qsqs ss tsts
ODM_MANIFEST_DSDS_FILES := $(DEVICE_PATH)/etc/vintf/odm/manifest_dsds.xml
ODM_MANIFEST_QSQS_FILES := $(DEVICE_PATH)/etc/vintf/odm/manifest_qsqs.xml
ODM_MANIFEST_SS_FILES := $(DEVICE_PATH)/etc/vintf/odm/manifest_ss.xml
ODM_MANIFEST_TSTS_FILES := $(DEVICE_PATH)/etc/vintf/odm/manifest_tsts.xml

# Modules
BOARD_RECOVERY_KERNEL_MODULES += $(wildcard $(DEVICE_PATH)/rootdir/modules/recovery/*.ko)
BOARD_VENDOR_KERNEL_MODULES += $(wildcard $(DEVICE_PATH)/rootdir/modules/vendor_dlkm/*.ko)
BOARD_VENDOR_RAMDISK_KERNEL_MODULES += $(wildcard $(DEVICE_PATH)/rootdir/modules/vendor_boot/*.ko)
BOARD_SYSTEM_DLKM_KERNEL_MODULES += $(wildcard $(DEVICE_PATH)/rootdir/modules/system_dlkm/*.ko)
BOARD_RECOVERY_KERNEL_MODULES_LOAD := $(shell cat $(DEVICE_PATH)/rootdir/modules/recovery/modules.load.recovery)
BOARD_VENDOR_KERNEL_MODULES_LOAD := $(shell cat $(DEVICE_PATH)/rootdir/modules/vendor_dlkm/modules.load)
BOARD_VENDOR_RAMDISK_KERNEL_MODULES_LOAD := $(shell cat $(DEVICE_PATH)/rootdir/modules/vendor_boot/modules.load.recovery)
BOARD_SYSTEM_DLKM_KERNEL_MODULES_LOAD := $(shell cat $(DEVICE_PATH)/rootdir/modules/system_dlkm/modules.load)

# Maintainer
PRODUCT_MAINTAINER := SavedByLight
